# arguments for dataset
dataset: mnms
nclass: 4
L2U_size: 224
data_root: ./MNMS_data_2d

# arguments for training
epochs: 300
batch_size: 4 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 5.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255

criterion_u:
  name: CELoss
  kwargs:
    ignore_index: 255

# arguments for model
model:
  backbone:
    type: model.backbone.messenger_transformer.mit_b5
    kwargs:
      embed_dims: [64, 128, 320, 512]
      pretrained: True
  decoder:
    type: model.semseg.segformerhead.SemiDecoder
    kwargs:
      num_layers: 2
      num_heads: 2
      num_class: 4
      in_planes: [64, 128, 320, 512]
      image_size: 224

replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]