# arguments for dataset
dataset: synapse
nclass: 14
crop_size: 512
cut_mix_size: 64
data_root: ./synapse

# arguments for training
epochs: 300
batch_size: 2 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 5.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255



criterion_u:
  name: CELoss
  kwargs:
    ignore_index: 255

# arguments for model
model:
  backbone:
    type: model.backbone.mit.mit_b5
    kwargs:
      embed_dims: [64, 128, 320, 512]
      pretrained: True
  transformer:
    type: model.semseg.sd_messenger.SDMessengerTransformer
    kwargs:
      num_layers: 2
      num_heads: 2
      num_class: 14
      in_planes: [64, 128, 320, 512]
      image_size: 512
      add_cross_attn: [False, False, False, True]

replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]